pub mod auto;
pub mod hdlc;
pub mod i2p;
pub mod serial;
pub mod tcp_client;
pub mod tcp_server;
pub mod udp;

use std::sync::Arc;

use tokio::sync::mpsc;
use tokio::task;
use tokio_util::sync::CancellationToken;

use reticulum_core::buffer::{InputBuffer, OutputBuffer};
use reticulum_core::hash::AddressHash;
use reticulum_core::hash::Hash;
use reticulum_core::packet::Packet;
use reticulum_core::serde::Serialize;

// ── Routing types (shared via reticulum-core) ─────────────────────────────────

/// Routing selector — controls which interface(s) receive a [`TxMessage`].
///
/// Re-exported from [`reticulum_core::routing`]; identical to the type used
/// by `reticulum-embassy`, enabling cross-runtime compatibility.
pub use reticulum_core::routing::TxMessageType;

/// An outbound packet destined for one or more interfaces.
///
/// Re-exported from [`reticulum_core::routing`].
pub use reticulum_core::routing::TxMessage;

/// A packet received from an interface, tagged with the interface's address.
///
/// Re-exported from [`reticulum_core::routing`].
pub use reticulum_core::routing::RxMessage;

// ── TokioInterface ────────────────────────────────────────────────────────────

/// A `Send`-capable async interface trait for use with the Tokio runtime.
///
/// This is a type alias for [`reticulum_core::interface::SendInterface`].
///
/// ## Why not use `reticulum_core::interface::Interface` directly?
///
/// The base [`Interface`] trait uses AFIT (async fn in trait), which generates
/// opaque future types whose `Send`-ness cannot be expressed as a bound on
/// stable Rust.  Tokio's multi-threaded scheduler requires futures to be
/// `Send + 'static` before they can be spawned.
///
/// `SendInterface` (generated by `trait_variant::make`) uses RPITIT so the
/// compiler can verify `+ Send` on the returned futures.  Every
/// `SendInterface` implementor automatically satisfies `Interface` through a
/// blanket impl.
///
/// ## Implementing
///
/// Implement `TokioInterface` (= `SendInterface`) on your concrete async I/O
/// type.  [`InterfaceManager::spawn_interface`] accepts any `TokioInterface`.
///
/// [`Interface`]: reticulum_core::interface::Interface
pub use reticulum_core::interface::SendInterface as TokioInterface;

pub type InterfaceTxSender = mpsc::Sender<TxMessage>;
pub type InterfaceTxReceiver = mpsc::Receiver<TxMessage>;

pub type InterfaceRxSender = mpsc::Sender<RxMessage>;
pub type InterfaceRxReceiver = mpsc::Receiver<RxMessage>;

pub struct InterfaceChannel {
    pub address: AddressHash,
    pub rx_channel: InterfaceRxSender,
    pub tx_channel: InterfaceTxReceiver,
    pub stop: CancellationToken,
}

impl InterfaceChannel {
    pub fn make_rx_channel(cap: usize) -> (InterfaceRxSender, InterfaceRxReceiver) {
        mpsc::channel(cap)
    }

    pub fn make_tx_channel(cap: usize) -> (InterfaceTxSender, InterfaceTxReceiver) {
        mpsc::channel(cap)
    }

    pub fn new(
        rx_channel: InterfaceRxSender,
        tx_channel: InterfaceTxReceiver,
        address: AddressHash,
        stop: CancellationToken,
    ) -> Self {
        Self {
            address,
            rx_channel,
            tx_channel,
            stop,
        }
    }

    pub fn address(&self) -> &AddressHash {
        &self.address
    }

    pub fn split(self) -> (InterfaceRxSender, InterfaceTxReceiver) {
        (self.rx_channel, self.tx_channel)
    }
}

// ── Generic interface driver ───────────────────────────────────────────────────

/// Drives any `TokioInterface` implementation.
///
/// Loops selecting between:
/// - `iface.receive()` → deserialises the frame into a `Packet` and forwards
///   it to the shared receive channel.
/// - `tx_recv.recv()` → serialises the outbound `Packet` and calls
///   `iface.transmit()`.
///
/// Exits when the cancellation token fires, the interface returns an error, or
/// the transmit channel is closed.
async fn drive_interface<I>(mut iface: I, channel: InterfaceChannel, cancel: CancellationToken)
where
    I: TokioInterface + 'static,
    I::Error: std::fmt::Debug + Send,
{
    let iface_addr = channel.address;
    let stop = channel.stop.clone();
    let (rx_send, mut tx_recv) = channel.split();

    log::debug!("iface {iface_addr}: driver started");

    loop {
        let mtu = TokioInterface::mtu(&iface);
        let mut buf = vec![0u8; mtu];

        tokio::select! {
            biased;

            _ = cancel.cancelled() => break,

            result = TokioInterface::receive(&mut iface, &mut buf) => {
                match result {
                    Ok(n) => {
                        match Packet::deserialize(&mut InputBuffer::new(&buf[..n])) {
                            Ok(packet) => {
                                // Non-blocking send: if the shared RX channel is
                                // full we drop the packet rather than blocking
                                // here.  Blocking in the receive arm of a biased
                                // select would starve the TX arm, eventually
                                // filling the TX queue and deadlocking the
                                // transport handler.
                                if rx_send
                                    .try_send(RxMessage { address: iface_addr, packet })
                                    .is_err()
                                {
                                    log::warn!("iface {iface_addr}: RX queue full, dropping inbound packet");
                                }
                            }
                            Err(e) => log::warn!("iface {iface_addr}: deserialise failed: {e:?}"),
                        }
                    }
                    Err(e) => {
                        log::warn!("iface {iface_addr}: receive error: {e:?}");
                        break;
                    }
                }
            }

            Some(msg) = tx_recv.recv() => {
                let mut out_buf = vec![0u8; TokioInterface::mtu(&iface)];
                let mut output = OutputBuffer::new(&mut out_buf);
                if msg.packet.serialize(&mut output).is_ok() {
                    if let Err(e) = TokioInterface::transmit(&mut iface, output.as_slice()).await {
                        log::warn!("iface {iface_addr}: transmit error: {e:?}");
                    }
                }
            }
        }
    }

    stop.cancel();
    log::debug!("iface {iface_addr}: driver stopped");
}

// ── InterfaceManager ──────────────────────────────────────────────────────────

struct LocalInterface {
    address: AddressHash,
    tx_send: InterfaceTxSender,
    stop: CancellationToken,
}

pub struct InterfaceManager {
    counter: usize,
    rx_recv: Arc<tokio::sync::Mutex<InterfaceRxReceiver>>,
    rx_send: InterfaceRxSender,
    cancel: CancellationToken,
    ifaces: Vec<LocalInterface>,
}

impl InterfaceManager {
    pub fn new(rx_cap: usize) -> Self {
        let (rx_send, rx_recv) = InterfaceChannel::make_rx_channel(rx_cap);
        let rx_recv = Arc::new(tokio::sync::Mutex::new(rx_recv));

        Self {
            counter: 0,
            rx_recv,
            rx_send,
            cancel: CancellationToken::new(),
            ifaces: Vec::new(),
        }
    }

    pub fn new_channel(&mut self, tx_cap: usize) -> InterfaceChannel {
        self.counter += 1;

        let counter_bytes = self.counter.to_le_bytes();
        let address = AddressHash::new_from_hash(&Hash::new_from_slice(&counter_bytes[..]));

        let (tx_send, tx_recv) = InterfaceChannel::make_tx_channel(tx_cap);

        log::debug!("iface: create channel {}", address);

        let stop = CancellationToken::new();

        self.ifaces.push(LocalInterface {
            address,
            tx_send,
            stop: stop.clone(),
        });

        InterfaceChannel {
            rx_channel: self.rx_send.clone(),
            tx_channel: tx_recv,
            address,
            stop,
        }
    }

    /// Register a [`TokioInterface`] implementation and spawn a generic driver
    /// task for it.
    ///
    /// Returns the `AddressHash` assigned to this interface, which can be used
    /// to route packets directly to it via [`send`](Self::send).
    pub fn spawn_interface<I>(&mut self, iface: I) -> AddressHash
    where
        I: TokioInterface + 'static,
        I::Error: std::fmt::Debug + Send,
    {
        let channel = self.new_channel(256);
        let address = *channel.address();
        let cancel = self.cancel.clone();
        task::spawn(drive_interface(iface, channel, cancel));
        address
    }

    pub fn receiver(&self) -> Arc<tokio::sync::Mutex<InterfaceRxReceiver>> {
        self.rx_recv.clone()
    }

    pub fn cleanup(&mut self) {
        self.ifaces.retain(|iface| !iface.stop.is_cancelled());
    }

    pub fn send(&self, message: TxMessage) {
        for iface in &self.ifaces {
            let should_send = match message.tx_type {
                TxMessageType::Broadcast(address) => address != Some(iface.address),
                TxMessageType::Direct(address) => address == iface.address,
            };

            if should_send && !iface.stop.is_cancelled() {
                if iface.tx_send.try_send(message).is_err() {
                    log::warn!("iface {}: TX queue full, dropping packet", iface.address);
                }
            }
        }
    }
}

impl Drop for InterfaceManager {
    fn drop(&mut self) {
        self.cancel.cancel();
    }
}
