///! Python compatibility tests
///!
///! These tests validate that the Rust implementation produces identical results
///! to the Python reference implementation using test vectors generated by Python tests.

use reticulum_core::hash::{AddressHash, Hash};
use reticulum_core::identity::Identity;
use reticulum_core::destination::DestinationName;
use ed25519_dalek::Signature;
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct HashFunctionsVector {
    input_hex: String,
    full_hash_hex: String,
    truncated_hash_hex: String,
    full_hash_length: usize,
    truncated_hash_length: usize,
}

#[derive(Deserialize)]
struct IdentityHashVector {
    public_key_hex: String,
    expected_hash_hex: String,
}

#[derive(Deserialize)]
struct SignatureVector {
    message_hex: String,
    public_key_hex: String,
    signature_hex: String,
    signature_length: usize,
}

#[derive(Deserialize)]
struct DestinationHashVector {
    identity_hex: String,
    app_name: String,
    aspects: Vec<String>,
    destination_hash_hex: String,
    name_hash_hex: String,
}

fn load_test_vector<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("../../tests/compat/vectors");
    path.push(format!("{}.json", name));

    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("Failed to read test vector: {:?}", path));

    serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("Failed to parse test vector {}: {}", name, e))
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn test_hash_functions_compat() {
    let vector: HashFunctionsVector = load_test_vector("hash_functions");

    let input = hex_to_bytes(&vector.input_hex);

    // Test full hash (SHA-256)
    let full_hash = Hash::new_from_slice(&input);
    let full_hash_hex = hex::encode(full_hash.as_slice());

    assert_eq!(
        full_hash_hex, vector.full_hash_hex,
        "Full hash mismatch"
    );
    assert_eq!(
        full_hash.as_slice().len(),
        vector.full_hash_length,
        "Full hash length mismatch"
    );

    // Test truncated hash (first 16 bytes)
    let truncated_hash = AddressHash::new_from_hash(&full_hash);
    let truncated_hex = hex::encode(truncated_hash.as_slice());

    assert_eq!(
        truncated_hex, vector.truncated_hash_hex,
        "Truncated hash mismatch"
    );
    assert_eq!(
        truncated_hash.as_slice().len(),
        vector.truncated_hash_length,
        "Truncated hash length mismatch"
    );

    println!("✓ Hash functions match Python implementation");
}

#[test]
fn test_identity_hash_compat() {
    let vector: IdentityHashVector = load_test_vector("identity_hash");

    let pub_key_bytes = hex_to_bytes(&vector.public_key_hex);

    // Python stores keys as: [X25519 public (32 bytes)][Ed25519 public (32 bytes)]
    assert_eq!(pub_key_bytes.len(), 64, "Public key should be 64 bytes");

    let x25519_key = &pub_key_bytes[0..32];
    let ed25519_key = &pub_key_bytes[32..64];

    // Create Identity from the public keys
    let _identity = Identity::new_from_slices(x25519_key, ed25519_key)
        .expect("valid identity from test vector");

    // Compute hash - should match Python's Identity.full_hash(pub_key)
    let identity_hash = Hash::new_from_slice(pub_key_bytes.as_slice());
    let hash_hex = hex::encode(identity_hash.as_slice());

    assert_eq!(
        hash_hex, vector.expected_hash_hex,
        "Identity hash mismatch"
    );

    println!("✓ Identity hash matches Python implementation");
}

#[test]
fn test_signature_verification_compat() {
    let vector: SignatureVector = load_test_vector("signature");

    let message = hex_to_bytes(&vector.message_hex);
    let pub_key_bytes = hex_to_bytes(&vector.public_key_hex);
    let signature_bytes = hex_to_bytes(&vector.signature_hex);

    assert_eq!(pub_key_bytes.len(), 64, "Public key should be 64 bytes");
    assert_eq!(signature_bytes.len(), 64, "Signature should be 64 bytes");

    let x25519_key = &pub_key_bytes[0..32];
    let ed25519_key = &pub_key_bytes[32..64];

    // Create Identity
    let identity = Identity::new_from_slices(x25519_key, ed25519_key)
        .expect("valid identity from test vector");

    // Parse signature
    let signature = Signature::from_slice(&signature_bytes)
        .expect("Failed to parse signature");

    // Verify signature matches
    let result = identity.verify(&message, &signature);

    assert!(
        result.is_ok(),
        "Signature verification failed: {:?}",
        result.err()
    );

    println!("✓ Signature verification matches Python implementation");
}

#[test]
fn test_destination_hash_compat() {
    let vector: DestinationHashVector = load_test_vector("destination_hash");

    let pub_key_bytes = hex_to_bytes(&vector.identity_hex);

    let x25519_key = &pub_key_bytes[0..32];
    let ed25519_key = &pub_key_bytes[32..64];

    // Create private identity (we only have public keys, but can still test name hash)
    let _identity_for_public = Identity::new_from_slices(x25519_key, ed25519_key)
        .expect("valid identity from test vector");

    // Create destination name
    // Python uses app_name + "." + aspect1 + "." + aspect2
    let aspects_str = vector.aspects.join(".");
    let name = DestinationName::new(&vector.app_name, &aspects_str);

    let name_hash_hex = hex::encode(name.as_name_hash_slice());

    // Python's name_hash is first 10 bytes
    let expected_name_hash = &vector.name_hash_hex[0..20]; // 10 bytes = 20 hex chars

    assert_eq!(
        &name_hash_hex[0..20],
        expected_name_hash,
        "Name hash mismatch"
    );

    println!("✓ Destination hash derivation matches Python implementation");
}
