//! Request/Response system for RPC-like communication over Reticulum links
//!
//! This module implements the request/response pattern used throughout the Reticulum ecosystem.
//! Requests are sent over established links and responses are routed back to the requester.
//!
//! # Request Lifecycle
//!
//! 1. Client creates a request with a path and optional data
//! 2. Request is sent over an active link with a unique request ID
//! 3. Server receives request, looks up registered handler for the path
//! 4. Handler processes request and generates response
//! 5. Response is sent back with the original request ID
//! 6. Client receives response and matches it to the original request
//!
//! # Example
//!
//! ```ignore
//! // Server side - register a request handler
//! destination.register_request_handler(
//!     "/status",
//!     |path, data, request_id, link_id, remote_identity, requested_at| {
//!         // Process request and return response data
//!         Some(b"OK".to_vec())
//!     },
//!     RequestPolicy::AllowAll,
//! );
//!
//! // Client side - send a request
//! let receipt = link.request(
//!     "/status",
//!     None,
//!     |response| {
//!         println!("Received response: {:?}", response);
//!     },
//! );
//! ```

#[cfg(feature = "alloc")]
use core::time::Duration;

use crate::{hash::Hash, identity::Identity, link::LinkId};

#[cfg(feature = "alloc")]
extern crate alloc;
#[cfg(feature = "alloc")]
use alloc::vec::Vec;

/// Request identifier - generated by hashing the request path
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub struct RequestId(pub Hash);

impl RequestId {
    /// Create a request ID by hashing the path
    pub fn from_path(path: &str) -> Self {
        Self(Hash::new_from_slice(path.as_bytes()))
    }

    /// Create request ID from hash bytes
    pub fn from_hash(hash: Hash) -> Self {
        Self(hash)
    }

    pub fn as_slice(&self) -> &[u8] {
        self.0.as_slice()
    }
}

/// Request access control policy
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum RequestPolicy {
    /// No requests allowed
    AllowNone,
    /// All requests allowed
    AllowAll,
    /// Only requests from specific identities allowed
    AllowList,
}

/// Request status
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum RequestStatus {
    /// Request has been sent, awaiting response
    Pending,
    /// Response received successfully
    Completed,
    /// Request timed out
    TimedOut,
    /// Request failed
    Failed,
}

/// Core request data structure.
///
/// The `path` field is only stored when the `alloc` feature is enabled.  On
/// `no_alloc` targets the request can still be identified by its [`id`]
/// (a hash of the path), which is always present.
///
/// [`id`]: RequestData::id
#[derive(Debug, Clone)]
pub struct RequestData {
    /// Request identifier (hash of the path)
    pub id: RequestId,
    /// Request path — only available with the `alloc` feature.
    #[cfg(feature = "alloc")]
    pub path: alloc::string::String,
    /// Link over which the request was sent
    pub link_id: LinkId,
    /// Timestamp when request was sent (milliseconds since epoch)
    pub sent_at: u64,
    /// Request timeout duration (milliseconds)
    pub timeout_ms: u64,
    /// Current status of the request
    pub status: RequestStatus,
}

impl RequestData {
    /// Create a new request (heap-allocated path storage).
    #[cfg(feature = "alloc")]
    pub fn new(path: &str, link_id: LinkId, timeout: Duration) -> Self {
        Self {
            id: RequestId::from_path(path),
            path: alloc::string::String::from(path),
            link_id,
            sent_at: 0,
            timeout_ms: timeout.as_millis() as u64,
            status: RequestStatus::Pending,
        }
    }

    /// Create a new request without storing the path string.
    ///
    /// Available on all targets (including `no_alloc`).  The path is hashed to
    /// produce the [`RequestId`] but is not retained.
    pub fn new_from_path(path: &str, link_id: LinkId, timeout_ms: u64) -> Self {
        Self {
            id: RequestId::from_path(path),
            #[cfg(feature = "alloc")]
            path: alloc::string::String::from(path),
            link_id,
            sent_at: 0,
            timeout_ms,
            status: RequestStatus::Pending,
        }
    }

    /// Check if the request has timed out
    pub fn is_timed_out(&self, current_time_ms: u64) -> bool {
        if self.status != RequestStatus::Pending {
            return false;
        }
        current_time_ms >= self.sent_at + self.timeout_ms
    }

    /// Mark request as completed
    pub fn mark_completed(&mut self) {
        self.status = RequestStatus::Completed;
    }

    /// Mark request as timed out
    pub fn mark_timed_out(&mut self) {
        self.status = RequestStatus::TimedOut;
    }

    /// Mark request as failed
    pub fn mark_failed(&mut self) {
        self.status = RequestStatus::Failed;
    }
}

/// Response data structure
#[derive(Debug, Clone)]
pub struct ResponseData {
    /// Request ID this response is for
    pub request_id: RequestId,
    /// Response payload — only available with the `alloc` feature.
    #[cfg(feature = "alloc")]
    pub data: Vec<u8>,
    /// Timestamp when response was received (milliseconds since epoch)
    pub received_at: u64,
}

#[cfg(feature = "alloc")]
impl ResponseData {
    pub fn new(request_id: RequestId, data: Vec<u8>) -> Self {
        Self {
            request_id,
            data,
            received_at: 0,
        }
    }
}

#[cfg(not(feature = "alloc"))]
impl ResponseData {
    /// Create a response without a payload (no_alloc path).
    pub fn new_empty(request_id: RequestId) -> Self {
        Self {
            request_id,
            received_at: 0,
        }
    }
}

/// Request handler context — information passed to request handlers.
#[derive(Clone)]
pub struct RequestContext {
    /// Request path — only available with the `alloc` feature.
    #[cfg(feature = "alloc")]
    pub path: alloc::string::String,
    /// Request data payload — only available with the `alloc` feature.
    #[cfg(feature = "alloc")]
    pub data: Option<Vec<u8>>,
    /// Request identifier
    pub request_id: RequestId,
    /// Link over which the request was received
    pub link_id: LinkId,
    /// Remote peer's identity
    pub remote_identity: Identity,
    /// Timestamp when request was received (milliseconds since epoch)
    pub requested_at: u64,
}

#[cfg(feature = "alloc")]
impl RequestContext {
    pub fn new(
        path: &str,
        data: Option<Vec<u8>>,
        request_id: RequestId,
        link_id: LinkId,
        remote_identity: Identity,
        requested_at: u64,
    ) -> Self {
        Self {
            path: alloc::string::String::from(path),
            data,
            request_id,
            link_id,
            remote_identity,
            requested_at,
        }
    }
}

#[cfg(not(feature = "alloc"))]
impl RequestContext {
    /// Create a request context without path/data storage (no_alloc path).
    pub fn new(
        request_id: RequestId,
        link_id: LinkId,
        remote_identity: Identity,
        requested_at: u64,
    ) -> Self {
        Self {
            request_id,
            link_id,
            remote_identity,
            requested_at,
        }
    }
}

/// Default request timeout (10 seconds)
pub const DEFAULT_REQUEST_TIMEOUT_MS: u64 = 10_000;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_request_id_from_path() {
        let id1 = RequestId::from_path("/test/path");
        let id2 = RequestId::from_path("/test/path");
        let id3 = RequestId::from_path("/different/path");

        assert_eq!(id1, id2);
        assert_ne!(id1, id3);
    }

    #[test]
    #[cfg(feature = "alloc")]
    fn test_request_timeout() {
        let link_id = LinkId::new_empty();
        let mut request = RequestData::new("/test", link_id, Duration::from_secs(5));
        request.sent_at = 1000;

        assert!(!request.is_timed_out(5999));
        assert!(request.is_timed_out(6000));
        assert!(request.is_timed_out(10000));
    }

    #[test]
    #[cfg(feature = "alloc")]
    fn test_request_status() {
        let link_id = LinkId::new_empty();
        let mut request = RequestData::new("/test", link_id, Duration::from_secs(5));

        assert_eq!(request.status, RequestStatus::Pending);

        request.mark_completed();
        assert_eq!(request.status, RequestStatus::Completed);
        assert!(!request.is_timed_out(u64::MAX));

        request.status = RequestStatus::Pending;
        request.mark_timed_out();
        assert_eq!(request.status, RequestStatus::TimedOut);

        request.status = RequestStatus::Pending;
        request.mark_failed();
        assert_eq!(request.status, RequestStatus::Failed);
    }

    #[test]
    #[cfg(feature = "alloc")]
    fn test_response_creation() {
        let request_id = RequestId::from_path("/test");
        let data = b"response data".to_vec();
        let response = ResponseData::new(request_id, data.clone());

        assert_eq!(response.request_id, request_id);
        assert_eq!(response.data, data);
    }

    #[test]
    #[cfg(feature = "alloc")]
    fn test_request_context() {
        let path = "/api/status";
        let data = Some(b"request data".to_vec());
        let request_id = RequestId::from_path(path);
        let link_id = LinkId::new_empty();
        let remote_identity = Identity::default();

        let context = RequestContext::new(
            path,
            data.clone(),
            request_id,
            link_id,
            remote_identity,
            12345,
        );

        assert_eq!(context.path, path);
        assert_eq!(context.data, data);
        assert_eq!(context.request_id, request_id);
        assert_eq!(context.requested_at, 12345);
    }
}
